import mailPipelineContractJson from '../flow-contracts/mail-pipeline.json'
import type { FlowConfig, FlowContract, SpanMapping } from '../core/types'
import { withNodeVisualDefaultsForFlow } from './nodeFactory'

const mailPipelineContract = mailPipelineContractJson as FlowContract

const workerBullets = ['1 worker at a time', '(configurable to n workers)']

export const spanMapping: SpanMapping = {
  'cron-scheduler': 'cron-scheduler',
  'backfill-queue': 'backfill-queue',
  'incoming-queue': 'incoming-queue',
  'analyze-queue': 'analyze-queue',
  'extract-queue': 'extract-queue',
  'actions-queue': 'actions-queue',
  'send-queue': 'send-queue',
  'backfill-worker': 'backfill-worker',
  'incoming-worker': 'incoming-worker',
  'analyze-worker': 'analyze-worker',
  'extract-worker': 'extract-worker',
  'recompute-worker': 'extract-worker',
  'actions-worker': 'actions-worker',
  'send-worker': 'send-worker',
  'incoming-schedule-process': 'incoming-schedule-process',
  'analyze-decision': 'analyze-decision',
  'draft-reply': 'draft-reply',
  'autosend-decision': 'autosend-decision',
  'send-process': 'send-process',

  // Legacy aliases kept so older replay fixtures and producer emissions still map.
  'batchfill-queue': 'backfill-queue',
  'batchfill-worker': 'backfill-worker',
  'check-process': 'incoming-schedule-process',

  'rrq:queue:mail-backfill': 'backfill-queue',
  'rrq:queue:mail-incoming': 'incoming-queue',
  'rrq:queue:mail-analyze': 'analyze-queue',
  'rrq:queue:mail-extract': 'extract-queue',
  'rrq:queue:mail-actions': 'actions-queue',
  'rrq:queue:mail-send': 'send-queue',

  'backfill.write_threads': 'backfill-worker',
  'backfill.write_metadata': 'backfill-worker',
  'incoming.write_threads': 'incoming-worker',
  'incoming.write_metadata': 'incoming-worker',
  'incoming.cursor_update': 'incoming-worker',
  'scheduler.cursor_update': 'incoming-schedule-process',
  'analyze.decision': 'analyze-decision',
  'analyze.reply_status_write': 'analyze-decision',
  'analyze.draft_insert': 'draft-reply',
  'analyze.draft_status_write': 'draft-reply',
  'analyze.autosend_decision': 'autosend-decision',
  'analyze.action_batch_auto_approve': 'autosend-decision',
  'analyze.execute_enqueue': 'actions-queue',
  'approval.execute_enqueue': 'actions-queue',
  'actions.execute_result': 'actions-worker',
  'actions.send_enqueue': 'actions-worker',
  'extract.upsert_contacts': 'extract-worker',
  'extract.recompute_enqueue': 'extract-worker',
  'extract.final_result': 'extract-worker',
  'extract.state_write': 'extract-worker',
  'recompute.started': 'extract-worker',
  'recompute.final_result': 'extract-worker',
  'send.precheck': 'send-process',
  'send.provider_call': 'send-process',
  'send.finalize': 'send-process',
  'send.final_result': 'send-process',

  handle_mail_backfill_start: 'backfill-worker',
  handle_mail_backfill_chunk: 'backfill-worker',
  handle_mail_incoming_check: 'incoming-worker',
  handle_mail_analyze_reply: 'analyze-worker',
  handle_mail_extract: 'extract-worker',
  handle_mail_recompute_opportunities: 'extract-worker',
  handle_mail_execute_approved_actions: 'actions-worker',
  handle_mail_send_reply: 'send-worker',
  handle_mail_cron_tick: 'cron-scheduler',

  mail_backfill: 'backfill-worker',
  mail_incoming: 'incoming-worker',
  mail_analyze: 'analyze-worker',
  mail_extract: 'extract-worker',
  mail_actions: 'actions-worker',
  mail_send: 'send-worker',
}

export const producerMapping: SpanMapping = {
  handle_mail_backfill_start: 'trigger-oauth',
  handle_mail_send_reply: 'enqueue-send-reply',
}

export const mailPipelineFlow: FlowConfig = {
  id: mailPipelineContract.id,
  name: mailPipelineContract.name,
  description: 'Real-time view of queue, worker, decision, and persistence steps for mail processing.',
  contract: mailPipelineContract,
  hasGraph: true,
  nodes: withNodeVisualDefaultsForFlow([
    {
      id: 'trigger-oauth',
      type: 'pill',
      label: 'vendor email account connected',
      sublabel: '(triggered by Fullstack -> integrations -> oauth flow)',
      position: { x: -270, y: -40 },
    },
    {
      id: 'backfill-queue',
      type: 'roundedRect',
      label: 'rrq:queue:mail-backfill',
      sublabel: '(read batches of email)',
      style: { icon: 'queue' },
      position: { x: 110, y: -70 },
      size: { width: 340 },
    },
    {
      id: 'backfill-note',
      type: 'annotation',
      label:
        '* uses mail_cursors.backfill_page_token to control paging\n- empty=start from first page\n- token=resume from that page\n- done marker=skip fetch/enqueue',
      position: { x: 485, y: -25 },
    },
    {
      id: 'backfill-worker',
      type: 'rectangle',
      label: 'mail_backfill',
      sublabel: 'workers',
      description: 'Backfills historical mail for newly connected accounts.',
      style: { icon: 'worker' },
      position: { x: 185, y: 60 },
      bullets: workerBullets,
      size: { width: 210 },
    },
    {
      id: 'cron-scheduler',
      type: 'roundedRect',
      label: 'rrq cron (scheduler)',
      sublabel: 'function: handle_mail_cron_tick',
      style: { icon: 'cron' },
      position: { x: 175, y: 220 },
      size: { width: 250 },
    },
    {
      id: 'cron-enqueue',
      type: 'badge',
      label: 'enqueue handle_mail_cron_tick (every 1 minute)',
      position: { x: 150, y: 320 },
      size: { width: 290 },
      handles: [
        { position: 'top', type: 'target' },
        { position: 'bottom', type: 'source' },
      ],
    },
    {
      id: 'incoming-queue',
      type: 'roundedRect',
      label: 'rrq:queue:mail-incoming',
      style: { icon: 'queue' },
      position: { x: 145, y: 405 },
      size: { width: 315 },
      handles: [
        { id: 'in-top', position: 'top', type: 'target' },
        { id: 'in-left', position: 'left', type: 'target' },
        { id: 'out-bottom', position: 'bottom', type: 'source' },
      ],
    },
    {
      id: 'incoming-queue-note',
      type: 'annotation',
      label:
        'contains both job types:\n- handle_mail_cron_tick\n- handle_mail_incoming_check\n* jobs can be from multiple vendors/mailboxes',
      position: { x: 490, y: 420 },
    },
    {
      id: 'incoming-worker',
      type: 'rectangle',
      label: 'mail_incoming',
      sublabel: 'workers',
      description: 'Checks connected inboxes for new mail and hands off downstream work.',
      style: { icon: 'worker' },
      position: { x: 205, y: 535 },
      bullets: workerBullets,
      size: { width: 210 },
      handles: [
        { position: 'top', type: 'target' },
        { id: 'out-left', position: 'left', type: 'source' },
        { id: 'out-right', position: 'right', type: 'source' },
        { id: 'out-bottom', position: 'bottom', type: 'source' },
      ],
    },
    {
      id: 'incoming-schedule-group',
      type: 'group',
      label: '',

      position: { x: -420, y: 670 },
      size: { width: 520, height: 320 },
    },
    {
      id: 'incoming-schedule-process',
      semanticRole: 'process',
      type: 'rectangle',
      label: 'schedule incoming checks',

      position: { x: 115, y: 32 },
      size: { width: 300 },
      parentId: 'incoming-schedule-group',
      bullets: ['find mailboxes to check', 'query mail_oauth_tokens', 'lookup mail_cursors'],
      handles: [
        { id: 'in-top', position: 'top', type: 'target' },
        { id: 'out-left', position: 'left', type: 'source' },
        { id: 'out-right', position: 'right', type: 'source' },
        { id: 'out-bottom', position: 'bottom', type: 'source' },
      ],
    },
    {
      id: 'incoming-check-enqueue',
      type: 'badge',
      label: 'enqueue handle_mail_incoming_check (unread mail)',

      position: { x: 55, y: 145 },
      parentId: 'incoming-schedule-group',
      size: { width: 270 },
      handles: [
        { id: 'in-top', position: 'top', type: 'target' },
        { id: 'out-left', position: 'left', type: 'source' },
      ],
    },
    {
      id: 'incoming-scheduled-at',
      type: 'rectangle',
      label: 'write mail_cursors.incoming_check_scheduled_at = now',

      position: { x: 60, y: 235 },
      parentId: 'incoming-schedule-group',
      size: { width: 360 },
      handles: [{ id: 'in-top', position: 'top', type: 'target' }],
    },
    {
      id: 'postgres-main',
      type: 'cylinder',
      label: 'postgres',

      position: { x: 250, y: 715 },
      handles: [
        { id: 'in-left', position: 'left', type: 'target' },
        { id: 'in-right', position: 'right', type: 'target' },
      ],
    },
    {
      id: 'persistence-group',
      type: 'group',
      label: '',

      position: { x: 470, y: 650 },
      size: { width: 430, height: 280 },
      handles: [
        { id: 'in-top', position: 'top', type: 'target' },
        { id: 'out-bottom', position: 'bottom', type: 'source' },
        { id: 'out-right', position: 'right', type: 'source' },
      ],
    },
    {
      id: 'thread-store-write',
      type: 'rectangle',
      label: 'write raw mail threads to thread store',

      position: { x: 55, y: 35 },
      parentId: 'persistence-group',
      size: { width: 320 },
    },
    {
      id: 'metadata-write',
      type: 'rectangle',
      label: 'write mail threads metadata',

      position: { x: 55, y: 135 },
      parentId: 'persistence-group',
      size: { width: 320 },
    },
    {
      id: 'baseline-note',
      type: 'annotation',
      label: 'if no incoming_history_id:\nwrite mail_cursors.incoming_history_id\nand stop',
      position: { x: 600, y: 560 },
    },
    {
      id: 'thread-store-note',
      type: 'annotation',
      label: '- 1 job corresponds to 1 mailbox\n- 1 mailbox can have 1..n mail threads',
      position: { x: 930, y: 700 },
    },
    {
      id: 's3',
      type: 'cylinder',
      label: 'S3',
      style: { icon: 's3' },
      position: { x: 950, y: 650 },
    },
    {
      id: 'incoming-normal-group',
      type: 'group',
      label: '',

      position: { x: 500, y: 970 },
      size: { width: 345, height: 240 },
      handles: [{ id: 'in-top', position: 'top', type: 'target' }],
    },
    {
      id: 'extract-enqueue',
      type: 'badge',
      label: 'enqueue handle_mail_extract',

      position: { x: 58, y: 28 },
      size: { width: 225 },
      parentId: 'incoming-normal-group',
      handles: [
        { id: 'in-top', position: 'top', type: 'target' },
        { id: 'out-right', position: 'right', type: 'source' },
      ],
    },
    {
      id: 'analyze-enqueue',
      type: 'badge',
      label: 'enqueue handle_mail_analyze_reply',

      position: { x: 40, y: 90 },
      size: { width: 260 },
      parentId: 'incoming-normal-group',
      handles: [
        { id: 'in-top', position: 'top', type: 'target' },
        { id: 'out-right', position: 'right', type: 'source' },
      ],
    },
    {
      id: 'update-history',
      type: 'rectangle',
      label: 'update incoming_history_id in mail_cursors',

      position: { x: 35, y: 152 },
      size: { width: 270 },
      parentId: 'incoming-normal-group',
      handles: [{ id: 'in-top', position: 'top', type: 'target' }],
    },
    {
      id: 'analyze-queue',
      type: 'roundedRect',
      label: 'rrq:queue:mail-analyze',
      style: { icon: 'queue' },
      position: { x: 980, y: 1010 },
      size: { width: 250 },
      layout: { order: 56 },
      handles: [
        { id: 'in-left', position: 'left', type: 'target' },
        { id: 'out-bottom', position: 'bottom', type: 'source' },
      ],
    },
    {
      id: 'analyze-worker',
      type: 'rectangle',
      label: 'mail_analyze',
      sublabel: 'workers',
      description: 'Analyzes extracted mail and decides whether to draft a reply.',
      style: { icon: 'worker' },
      position: { x: 1005, y: 1160 },
      bullets: workerBullets,
      size: { width: 210 },
      layout: { lane: 'main', order: 58 },
    },
    {
      id: 'analyze-decision',
      type: 'diamond',
      label: 'analyze reply decision\n(propose mode)',
      style: { borderStyle: 'dashed' },
      position: { x: 1035, y: 1355 },
      layout: { lane: 'main', order: 60 },
    },
    {
      id: 'analyze-note',
      type: 'annotation',
      label: '- prechecks before LLM\n- LLM can return skip / needs_review / draft_reply',
      position: { x: 1275, y: 1285 },
      layout: { anchor: { targetId: 'analyze-decision', dx: 240, dy: -70 } },
    },
    {
      id: 'analyze-exception-label',
      type: 'annotation',
      label: 'other outcomes',
      position: { x: 1270, y: 1370 },
      layout: { anchor: { targetId: 'skip-owner-stop', dx: -8, dy: -34 } },
    },
    {
      id: 'skip-owner-stop',
      type: 'rectangle',
      label: 'if latest sender is mailbox owner:\nskip and stop',

      position: { x: 1275, y: 1370 },
      size: { width: 280 },
      layout: { lane: 'branch', order: 61, branch: { anchorId: 'analyze-decision', track: 'right', rank: 0, domain: 'analyze', column: 0 } },
    },
    {
      id: 'reuse-batch-stop',
      type: 'rectangle',
      label: 'if existing active action batch:\nreuse batch and stop',

      position: { x: 1300, y: 1470 },
      size: { width: 280 },
      layout: { lane: 'branch', order: 62, branch: { anchorId: 'analyze-decision', track: 'right', rank: 1, domain: 'analyze', column: 0 } },
    },
    {
      id: 'skip-thread-status',
      type: 'rectangle',
      label: 'set thread status = skipped',

      position: { x: 1310, y: 1570 },
      size: { width: 220 },
      layout: { lane: 'branch', order: 63, branch: { anchorId: 'analyze-decision', track: 'right', rank: 2, domain: 'analyze', column: 0 } },
    },
    {
      id: 'analyze-error',
      type: 'rectangle',
      label: 'decision error or malformed output\n-> set thread status = needs_review',

      position: { x: 1210, y: 1665 },
      size: { width: 310 },
      layout: { lane: 'branch', order: 66, branch: { anchorId: 'analyze-decision', track: 'right', rank: 3, domain: 'analyze', column: 0, dx: 0, dy: 8 } },
    },
    {
      id: 'supported-actions',
      type: 'diamond',
      label: 'Any supported\nproposed\nactions?',
      style: { borderStyle: 'dashed' },
      position: { x: 1035, y: 1595 },
      layout: { lane: 'main', order: 64, branch: { anchorId: 'analyze-decision', track: 'primary', rank: 0 } },
    },
    {
      id: 'draft-reply',
      semanticRole: 'process',
      type: 'rectangle',
      label: 'draft reply',
      sublabel: 'mail_reply_drafts',

      position: { x: 930, y: 1780 },
      size: { width: 190 },
      layout: { lane: 'main', order: 68, branch: { anchorId: 'supported-actions-outcome', track: 'primary', rank: 0 } },
    },
    {
      id: 'unsupported-actions-outcome',
      type: 'rectangle',
      label:
        '- insert reply draft\n- set draft status = needs_review\n- set initial thread status = needs_review',

      position: { x: 1270, y: 1780 },
      size: { width: 360 },
      layout: { lane: 'branch', order: 65, branch: { anchorId: 'supported-actions', track: 'right', rank: 0, domain: 'analyze', column: 0, dx: 10 } },
    },
    {
      id: 'pause-manual-review',
      type: 'rectangle',
      label: 'PAUSE\nawait manual review',

      position: { x: 1335, y: 1940 },
      size: { width: 200, height: 96 },
      layout: { lane: 'branch', order: 67, branch: { anchorId: 'unsupported-actions-outcome', track: 'primary', rank: 0, dy: 4 } },
    },
    {
      id: 'supported-actions-outcome',
      type: 'rectangle',
      label:
        '- insert reply draft\n- set draft status = approval_pending\n- create action batch\n- set initial thread status = pending_action_approval',

      position: { x: 875, y: 1945 },
      size: { width: 420 },
      layout: { lane: 'main', order: 70, branch: { anchorId: 'supported-actions', track: 'primary', rank: 0, dy: 10 } },
    },
    {
      id: 'autosend-decision',
      type: 'diamond',
      label: 'Autosend\nenabled and\nbatch auto-\napprovable?',
      style: { borderStyle: 'dashed' },
      position: { x: 1035, y: 2145 },
      layout: { lane: 'main', order: 72, branch: { anchorId: 'draft-reply', track: 'primary', rank: 0 } },
    },
    {
      id: 'pause-manual-approval',
      type: 'rectangle',
      label: 'PAUSE\nawait manual approval',

      position: { x: 1290, y: 2195 },
      size: { width: 210, height: 96 },
      layout: { lane: 'branch', order: 73, branch: { anchorId: 'autosend-decision', track: 'right', rank: 0, domain: 'approval', column: 0, dx: 10 } },
    },
    {
      id: 'manual-approval-api',
      type: 'rectangle',
      label: 'manual approval API\napprove batch + enqueue\nExecuteApprovedActionsJob',

      position: { x: 1280, y: 2335 },
      size: { width: 245 },
      layout: { lane: 'branch', order: 74, branch: { anchorId: 'pause-manual-approval', track: 'primary', rank: 0 } },
    },
    {
      id: 'autosend-approved',
      type: 'rectangle',
      label:
        '- approve action batch\n- set thread status = executing_actions\n- enqueue ExecuteApprovedActionsJob',

      position: { x: 835, y: 2325 },
      size: { width: 360 },
      layout: { lane: 'main', order: 76, branch: { anchorId: 'autosend-decision', track: 'primary', rank: 0, dy: 6 } },
    },
    {
      id: 'actions-queue',
      type: 'roundedRect',
      label: 'rrq:queue:mail-actions',
      style: { icon: 'queue' },
      position: { x: 985, y: 2525 },
      size: { width: 250 },
      layout: { lane: 'main', order: 77 },
      handles: [
        { id: 'in-top', position: 'top', type: 'target' },
        { id: 'out-bottom', position: 'bottom', type: 'source' },
      ],
    },
    {
      id: 'actions-worker',
      type: 'rectangle',
      label: 'mail_actions',
      sublabel: 'workers',
      description: 'Executes approved actions and hands off send jobs.',
      style: { icon: 'worker' },
      position: { x: 1005, y: 2670 },
      bullets: workerBullets,
      size: { width: 210 },
      layout: { lane: 'main', order: 78 },
    },
    {
      id: 'actions-process-group',
      type: 'group',
      label: '',

      position: { x: 895, y: 2820 },
      size: { width: 430, height: 255 },
    },
    {
      id: 'process-approved-action',
      type: 'rectangle',
      label: 'process approved send action',

      position: { x: 82, y: 24 },
      size: { width: 260 },
      parentId: 'actions-process-group',
    },
    {
      id: 'mark-draft-needs-review',
      type: 'rectangle',
      label: 'set draft status = needs_review',

      position: { x: 82, y: 103 },
      size: { width: 260 },
      parentId: 'actions-process-group',
    },
    {
      id: 'enqueue-send-reply',
      type: 'rectangle',
      label: 'enqueue handle_mail_send_reply ->\nset thread status = sending',

      position: { x: 82, y: 177 },
      size: { width: 260 },
      parentId: 'actions-process-group',
    },
    {
      id: 'extract-queue',
      type: 'roundedRect',
      label: 'rrq:queue:mail-extract',
      style: { icon: 'queue' },
      position: { x: 1565, y: 900 },
      size: { width: 250 },
      layout: { lane: 'sidecar', order: 64 },
      handles: [
        { id: 'in-left', position: 'left', type: 'target' },
        { id: 'out-bottom', position: 'bottom', type: 'source' },
      ],
    },
    {
      id: 'extract-creds-note',
      type: 'annotation',
      label:
        'contains both job types:\n- handle_mail_extract\n- handle_mail_recompute_opportunities\n\n* AI provider creds required for handle_mail_extract only',
      position: { x: 1825, y: 915 },
      layout: { anchor: { targetId: 'extract-queue', dx: 260, dy: 15 } },
    },
    {
      id: 'extract-worker',
      type: 'rectangle',
      label: 'mail_extract',
      sublabel: 'workers',
      description: 'Extracts structured contact and thread details from stored mail.',
      style: { icon: 'worker' },
      position: { x: 1580, y: 1035 },
      bullets: workerBullets,
      size: { width: 210 },
      layout: { lane: 'sidecar', order: 68 },
    },
    {
      id: 'extract-ai',
      type: 'rectangle',
      label: 'fetch thread from thread store (S3 or local)\nAI extraction',
      style: { borderStyle: 'dashed' },
      position: { x: 1545, y: 1215 },
      size: { width: 300 },
      layout: { lane: 'sidecar', order: 70 },
    },
    {
      id: 'extract-ai-success',
      type: 'diamond',
      label: 'AI extract\nsucceeded?',
      style: { borderStyle: 'dashed' },
      position: { x: 1615, y: 1405 },
      layout: { lane: 'sidecar', order: 72, branch: { anchorId: 'extract-ai', track: 'primary', rank: 0 } },
    },
    {
      id: 'extract-fail-1',
      type: 'rectangle',
      label: '- record_extract_state(error)\n- return Err (job retry)',

      position: { x: 1905, y: 1455 },
      size: { width: 215 },
      layout: { lane: 'branch', order: 73, branch: { anchorId: 'extract-ai-success', track: 'right', rank: 0, domain: 'extract', column: 1 } },
    },
    {
      id: 'upsert-contacts',
      type: 'badge',
      label: 'upsert_contacts() to\nmail_extracted_contacts',

      position: { x: 1535, y: 1605 },
      size: { width: 220 },
      layout: { lane: 'sidecar', order: 74, branch: { anchorId: 'extract-ai-success', track: 'primary', rank: 0 } },
    },
    {
      id: 'extract-upsert-note',
      type: 'annotation',
      label:
        '- normalize emails\n- dedupe per thread\n- prefer higher-confidence / richer non-empty fields\n- never overwrite non-empty stored fields with empty',
      position: { x: 1790, y: 1585 },
      layout: { anchor: { targetId: 'upsert-contacts', dx: 250, dy: -20 } },
    },
    {
      id: 'postgres-extract',
      type: 'cylinder',
      label: 'postgres',

      position: { x: 2050, y: 1635 },
      layout: { lane: 'resource', order: 75 },
      handles: [{ id: 'in-left', position: 'left', type: 'target' }],
    },
    {
      id: 'contact-upsert-success',
      type: 'diamond',
      label: 'contact\nupsert\nsuccessful?',
      style: { borderStyle: 'dashed' },
      position: { x: 1615, y: 1795 },
      layout: { lane: 'sidecar', order: 76, branch: { anchorId: 'upsert-contacts', track: 'primary', rank: 0 } },
    },
    {
      id: 'extract-fail-2',
      type: 'rectangle',
      label: '- record_extract_state(error)\n- return Err (job retry)',

      position: { x: 1905, y: 1850 },
      size: { width: 215 },
      layout: { lane: 'branch', order: 77, branch: { anchorId: 'contact-upsert-success', track: 'right', rank: 0, domain: 'extract', column: 1 } },
    },
    {
      id: 'extract-record-success',
      type: 'rectangle',
      label: 'record_extract_state(customers_count)',

      position: { x: 1535, y: 1995 },
      size: { width: 260 },
      layout: { lane: 'sidecar', order: 78, branch: { anchorId: 'contact-upsert-success', track: 'primary', rank: 0 } },
    },
    {
      id: 'recompute-enqueue',
      type: 'badge',
      label: 'enqueue\nhandle_mail_recompute_opportunities\n(debounced per mailbox)',

      position: { x: 1825, y: 1965 },
      size: { width: 320 },
      layout: { lane: 'branch', order: 79, branch: { anchorId: 'contact-upsert-success', track: 'right', rank: 1, domain: 'extract', column: 1, dx: -10 } },
      handles: [
        { position: 'top', type: 'target' },
        { position: 'left', type: 'source' },
      ],
    },
    {
      id: 'recompute-process',
      semanticRole: 'process',
      type: 'rectangle',
      label: 'recompute\nfollow_up_opportunities',

      position: { x: 1845, y: 1180 },
      size: { width: 240 },
      layout: { lane: 'branch', order: 69, branch: { anchorId: 'extract-worker', track: 'right', rank: 0, domain: 'extract', column: 1, dx: -20, dy: -12 } },
    },
    {
      id: 'recompute-note',
      type: 'annotation',
      label:
        '- scan mail_extracted_contacts for mailbox\n- upsert/delete follow_up_opportunities',
      position: { x: 2125, y: 1210 },
      layout: { anchor: { targetId: 'recompute-process', dx: 280, dy: 20 } },
    },
    {
      id: 'send-queue',
      type: 'roundedRect',
      label: 'rrq:queue:mail-send',
      style: { icon: 'queue' },
      position: { x: 985, y: 3135 },
      size: { width: 250 },
      handles: [
        { id: 'in-top', position: 'top', type: 'target' },
        { id: 'out-bottom', position: 'bottom', type: 'source' },
      ],
    },
    {
      id: 'send-worker',
      type: 'rectangle',
      label: 'mail_send',
      sublabel: 'workers',
      description: 'Validates and sends reply drafts through the provider.',
      style: { icon: 'worker' },
      position: { x: 1005, y: 3280 },
      bullets: workerBullets,
      size: { width: 210 },
    },
    {
      id: 'send-process',
      semanticRole: 'process',
      type: 'rectangle',
      label: 'handle_mail_send_reply',

      position: { x: 1005, y: 3450 },
      size: { width: 210 },
    },
    {
      id: 'send-process-group',
      type: 'group',
      label: '',

      position: { x: 615, y: 3580 },
      size: { width: 820, height: 430 },
      handles: [],
    },
    {
      id: 'send-prechecks',
      type: 'rectangle',
      label:
        'Pre-send checks: idempotency, freshness,\nGmail send scope, recipient, token, body ->\nGmail API send',

      position: { x: 210, y: 40 },
      size: { width: 400 },
      parentId: 'send-process-group',
    },
    {
      id: 'send-success',
      type: 'rectangle',
      label: 'set draft status = sent;\nset thread status = sent',

      position: { x: 30, y: 170 },
      size: { width: 250 },
      parentId: 'send-process-group',
    },
    {
      id: 'send-nonretry',
      type: 'rectangle',
      label: 'set draft status = send_failed;\nset thread status = send_failed or stale',

      position: { x: 260, y: 300 },
      size: { width: 300 },
      parentId: 'send-process-group',
    },
    {
      id: 'send-retry',
      type: 'rectangle',
      label: 'set draft status = needs_review;\nset thread status = needs_review',

      position: { x: 580, y: 170 },
      size: { width: 250 },
      parentId: 'send-process-group',
    },
  ]),

  edges: [
    { id: 'e-trigger-backfill', source: 'trigger-oauth', target: 'backfill-queue', type: 'dashed' },
    { id: 'e-backfill-q-worker', source: 'backfill-queue', target: 'backfill-worker' },
    { id: 'e-backfill-persist', source: 'backfill-worker', target: 'persistence-group', targetHandle: 'persistence-group-in-top' },

    { id: 'e-cron-enqueue', source: 'cron-scheduler', target: 'cron-enqueue' },
    { id: 'e-cron-enqueue-incoming', source: 'cron-enqueue', target: 'incoming-queue', targetHandle: 'incoming-queue-in-top' },
    { id: 'e-incoming-q-worker', source: 'incoming-queue', sourceHandle: 'incoming-queue-out-bottom', target: 'incoming-worker' },

    {
      id: 'e-incoming-worker-schedule',
      source: 'incoming-worker',
      sourceHandle: 'incoming-worker-out-left',
      target: 'incoming-schedule-process',
      targetHandle: 'incoming-schedule-process-in-top',
      label: 'execute handle_mail_cron_tick',
    },
    {
      id: 'e-schedule-enqueue',
      source: 'incoming-schedule-process',
      sourceHandle: 'incoming-schedule-process-out-left',
      target: 'incoming-check-enqueue',
      targetHandle: 'incoming-check-enqueue-in-top',
    },
    {
      id: 'e-schedule-cursor',
      source: 'incoming-schedule-process',
      sourceHandle: 'incoming-schedule-process-out-bottom',
      target: 'incoming-scheduled-at',
      targetHandle: 'incoming-scheduled-at-in-top',
    },
    {
      id: 'e-schedule-postgres',
      source: 'incoming-schedule-process',
      sourceHandle: 'incoming-schedule-process-out-right',
      target: 'postgres-main',
      targetHandle: 'postgres-main-in-left',
      label: 'lookup + cursor writes',
    },
    {
      id: 'e-incoming-check-enqueue-queue',
      source: 'incoming-check-enqueue',
      sourceHandle: 'incoming-check-enqueue-out-left',
      target: 'incoming-queue',
      targetHandle: 'incoming-queue-in-left',
    },

    {
      id: 'e-incoming-worker-persist',
      source: 'incoming-worker',
      sourceHandle: 'incoming-worker-out-right',
      target: 'persistence-group',
      targetHandle: 'persistence-group-in-top',
      label: 'execute handle_mail_incoming_check',
    },
    {
      id: 'e-persist-postgres',
      source: 'metadata-write',
      target: 'postgres-main',
      targetHandle: 'postgres-main-in-right',
      label: 'write metadata',
      type: 'dashed',
    },
    { id: 'e-persist-s3', source: 'thread-store-write', target: 's3', label: 'thread store', type: 'dashed' },
    {
      id: 'e-persist-incoming-normal',
      source: 'persistence-group',
      sourceHandle: 'persistence-group-out-bottom',
      target: 'incoming-normal-group',
      targetHandle: 'incoming-normal-group-in-top',
    },
    {
      id: 'e-persist-extract-queue',
      source: 'persistence-group',
      sourceHandle: 'persistence-group-out-right',
      target: 'extract-queue',
      targetHandle: 'extract-queue-in-left',
      label: 'backfill: enqueue handle_mail_extract',
      type: 'dashed',
    },
    {
      id: 'e-analyze-enqueue-queue',
      source: 'analyze-enqueue',
      sourceHandle: 'analyze-enqueue-out-right',
      target: 'analyze-queue',
      targetHandle: 'analyze-queue-in-left',
    },
    {
      id: 'e-extract-enqueue-queue',
      source: 'extract-enqueue',
      sourceHandle: 'extract-enqueue-out-right',
      target: 'extract-queue',
      targetHandle: 'extract-queue-in-left',
    },

    { id: 'e-analyze-q-worker', source: 'analyze-queue', sourceHandle: 'analyze-queue-out-bottom', target: 'analyze-worker' },
    { id: 'e-analyze-worker-decision', source: 'analyze-worker', target: 'analyze-decision', targetHandle: 'analyze-decision-in-top' },
    { id: 'e-analyze-skip-owner', source: 'analyze-decision', sourceHandle: 'analyze-decision-out-right', target: 'skip-owner-stop', type: 'dashed' },
    { id: 'e-analyze-reuse-batch', source: 'analyze-decision', sourceHandle: 'analyze-decision-out-right', target: 'reuse-batch-stop', type: 'dashed' },
    {
      id: 'e-analyze-skip-status',
      source: 'analyze-decision',
      sourceHandle: 'analyze-decision-out-right',
      target: 'skip-thread-status',
      label: 'action = skip',
      type: 'dashed',
    },
    {
      id: 'e-analyze-error',
      source: 'analyze-decision',
      sourceHandle: 'analyze-decision-out-right',
      target: 'analyze-error',
      type: 'dashed',
    },
    {
      id: 'e-analyze-supported-actions',
      source: 'analyze-decision',
      sourceHandle: 'analyze-decision-out-bottom',
      target: 'supported-actions',
      targetHandle: 'supported-actions-in-top',
      label: 'action = draft_reply',
    },
    {
      id: 'e-supported-actions-no',
      source: 'supported-actions',
      sourceHandle: 'supported-actions-out-right',
      target: 'unsupported-actions-outcome',
      label: 'No',
      type: 'dashed',
    },
    {
      id: 'e-supported-actions-yes',
      source: 'supported-actions',
      sourceHandle: 'supported-actions-out-bottom',
      target: 'supported-actions-outcome',
      label: 'Yes',
    },
    { id: 'e-unsupported-pause', source: 'unsupported-actions-outcome', target: 'pause-manual-review' },
    { id: 'e-supported-draft', source: 'supported-actions-outcome', target: 'draft-reply' },
    { id: 'e-draft-autosend', source: 'draft-reply', target: 'autosend-decision', targetHandle: 'autosend-decision-in-top' },
    {
      id: 'e-autosend-pause',
      source: 'autosend-decision',
      sourceHandle: 'autosend-decision-out-right',
      target: 'pause-manual-approval',
      label: 'No',
      type: 'dashed',
    },
    {
      id: 'e-autosend-approve',
      source: 'autosend-decision',
      sourceHandle: 'autosend-decision-out-bottom',
      target: 'autosend-approved',
      label: 'Yes',
    },
    { id: 'e-pause-manual-api', source: 'pause-manual-approval', target: 'manual-approval-api' },
    { id: 'e-autosend-actions', source: 'autosend-approved', target: 'actions-queue', targetHandle: 'actions-queue-in-top', type: 'dashed' },
    { id: 'e-manual-actions', source: 'manual-approval-api', target: 'actions-queue', targetHandle: 'actions-queue-in-top', type: 'dashed' },
    { id: 'e-actions-q-worker', source: 'actions-queue', sourceHandle: 'actions-queue-out-bottom', target: 'actions-worker' },
    { id: 'e-actions-worker-process', source: 'actions-worker', target: 'process-approved-action' },
    { id: 'e-actions-mark-review', source: 'process-approved-action', target: 'mark-draft-needs-review' },
    { id: 'e-actions-enqueue-send', source: 'mark-draft-needs-review', target: 'enqueue-send-reply' },
    { id: 'e-actions-send', source: 'enqueue-send-reply', target: 'send-queue', targetHandle: 'send-queue-in-top' },

    { id: 'e-extract-q-worker', source: 'extract-queue', sourceHandle: 'extract-queue-out-bottom', target: 'extract-worker' },
    { id: 'e-extract-worker-ai', source: 'extract-worker', target: 'extract-ai' },
    { id: 'e-extract-ai-success', source: 'extract-ai', target: 'extract-ai-success', targetHandle: 'extract-ai-success-in-top' },
    {
      id: 'e-extract-fail-1',
      source: 'extract-ai-success',
      sourceHandle: 'extract-ai-success-out-right',
      target: 'extract-fail-1',
      label: 'No',
      type: 'dashed',
    },
    {
      id: 'e-extract-upsert',
      source: 'extract-ai-success',
      sourceHandle: 'extract-ai-success-out-bottom',
      target: 'upsert-contacts',
      label: 'Yes',
    },
    { id: 'e-upsert-postgres', source: 'upsert-contacts', target: 'postgres-extract', targetHandle: 'postgres-extract-in-left', type: 'dashed' },
    { id: 'e-upsert-success', source: 'upsert-contacts', target: 'contact-upsert-success', targetHandle: 'contact-upsert-success-in-top' },
    {
      id: 'e-extract-fail-2',
      source: 'contact-upsert-success',
      sourceHandle: 'contact-upsert-success-out-right',
      target: 'extract-fail-2',
      label: 'No',
      type: 'dashed',
    },
    {
      id: 'e-extract-record-success',
      source: 'contact-upsert-success',
      sourceHandle: 'contact-upsert-success-out-bottom',
      target: 'extract-record-success',
      label: 'Yes',
    },
    {
      id: 'e-extract-recompute-enqueue',
      source: 'contact-upsert-success',
      sourceHandle: 'contact-upsert-success-out-bottom',
      target: 'recompute-enqueue',
      type: 'dashed',
    },
    {
      id: 'e-recompute-enqueue-queue',
      source: 'recompute-enqueue',
      target: 'extract-queue',
      targetHandle: 'extract-queue-in-left',
      type: 'dashed',
    },
    {
      id: 'e-extract-worker-recompute',
      source: 'extract-worker',
      target: 'recompute-process',
      label: 'execute handle_mail_recompute_opportunities',
      type: 'dashed',
    },

    { id: 'e-send-q-worker', source: 'send-queue', sourceHandle: 'send-queue-out-bottom', target: 'send-worker' },
    { id: 'e-send-worker-process', source: 'send-worker', target: 'send-process' },
    { id: 'e-send-process-prechecks', source: 'send-process', target: 'send-prechecks' },
    {
      id: 'e-send-success-branch',
      source: 'send-prechecks',
      target: 'send-success',
      label: 'success',
      type: 'dashed',
    },
    {
      id: 'e-send-retry-branch',
      source: 'send-prechecks',
      target: 'send-retry',
      label: 'retryable failure',
      type: 'dashed',
    },
    {
      id: 'e-send-nonretry-branch',
      source: 'send-prechecks',
      target: 'send-nonretry',
      label: 'non-retryable failure',
      type: 'dashed',
    },
  ],
  producerMapping,
  spanMapping,
}
