import mailPipelineContractJson from '../flow-contracts/mail-pipeline.json'
import type { FlowConfig, FlowContract, SpanMapping } from '../core/types'
import { triggerNode, queueNode, workerNode, schedulerNode, stepNode, decisionNode, resourceNode, detailGroup, detailNode } from './nodeFactory'

const mailPipelineContract = mailPipelineContractJson as FlowContract

const workerBullets = ['1 worker at a time', '(configurable to n workers)']

export const spanMapping: SpanMapping = {
  'cron-scheduler': 'cron-scheduler',
  'backfill-queue': 'backfill-queue',
  'incoming-queue': 'incoming-queue',
  'analyze-queue': 'analyze-queue',
  'extract-queue': 'extract-queue',
  'actions-queue': 'actions-queue',
  'send-queue': 'send-queue',
  'backfill-worker': 'backfill-worker',
  'incoming-worker': 'incoming-worker',
  'analyze-worker': 'analyze-worker',
  'extract-worker': 'extract-worker',
  'recompute-worker': 'extract-worker',
  'actions-worker': 'actions-worker',
  'send-worker': 'send-worker',
  'incoming-schedule-process': 'incoming-schedule-process',
  'analyze-decision': 'analyze-decision',
  'draft-reply': 'draft-reply',
  'autosend-decision': 'autosend-decision',
  'send-process': 'send-process',

  'rrq:queue:mail-backfill': 'backfill-queue',
  'rrq:queue:mail-incoming': 'incoming-queue',
  'rrq:queue:mail-analyze': 'analyze-queue',
  'rrq:queue:mail-extract': 'extract-queue',
  'rrq:queue:mail-actions': 'actions-queue',
  'rrq:queue:mail-send': 'send-queue',

  'backfill-worker.write-threads': 'backfill-worker',
  'backfill-worker.write-metadata': 'backfill-worker',
  'incoming-worker.write-threads': 'incoming-worker',
  'incoming-worker.write-metadata': 'incoming-worker',
  'incoming-worker.cursor-update': 'incoming-worker',
  'incoming-schedule-process.cursor-update': 'incoming-scheduled-at',
  'analyze-decision.final-result': 'analyze-decision',
  'analyze-decision.reply-status-write': 'analyze-decision',
  'draft-reply.draft-insert': 'draft-reply',
  'draft-reply.draft-status-write': 'draft-reply',
  'autosend-decision.action-batch-auto-approve': 'autosend-decision',
  'autosend-decision.execute-enqueue': 'actions-queue',
  'autosend-decision.execute-result': 'autosend-decision',
  'autosend-decision.send-enqueue': 'autosend-decision',
  'extract-worker.resolve-identity': 'extract-worker',
  'extract-worker.recompute-enqueue': 'extract-worker',
  'extract-worker.started': 'extract-worker',
  'extract-worker.upsert-contacts': 'extract-worker',
  'extract-worker.upsert-insights': 'extract-worker',
  'extract-worker.final-result': 'extract-worker',
  'extract-worker.state-write': 'extract-worker',
  'send-process.precheck': 'send-process',
  'send-process.provider-call': 'send-process',
  'send-process.finalize': 'send-process',
  'send-process.final-result': 'send-process',

  handle_mail_backfill_start: 'backfill-worker',
  handle_mail_backfill_chunk: 'backfill-worker',
  handle_mail_incoming_check: 'incoming-worker',
  handle_mail_analyze_reply: 'analyze-worker',
  handle_mail_extract: 'extract-worker',
  handle_mail_recompute_opportunities: 'extract-worker',
  handle_mail_execute_approved_actions: 'actions-worker',
  handle_mail_send_reply: 'send-worker',
  handle_mail_cron_tick: 'cron-scheduler',

  mail_backfill: 'backfill-worker',
  mail_incoming: 'incoming-worker',
  mail_analyze: 'analyze-worker',
  mail_extract: 'extract-worker',
  mail_actions: 'actions-worker',
  mail_send: 'send-worker',
}

export const producerMapping: SpanMapping = {
  handle_mail_backfill_start: 'trigger-oauth',
  handle_mail_send_reply: 'enqueue-send-reply',
}

export const mailPipelineFlow: FlowConfig = {
  id: mailPipelineContract.id,
  name: mailPipelineContract.name,
  description: 'Real-time view of queue, worker, decision, and persistence steps for mail processing.',
  contract: mailPipelineContract,
  hasGraph: true,
  seedPositions: {
    'trigger-oauth': { x: 497.2185169912251, y: 63.970854074023975 },
    'backfill-queue': { x: 496.427472338474, y: 166.85027871802492 },
    'backfill-worker': { x: 497.4628971983349, y: 282.7818969490317 },
    'cron-scheduler': { x: 41.24359816721122, y: 77.57274249611953 },
    'cron-enqueue': { x: 40.53759037822563, y: 194.0598634109286 },
    'incoming-queue': { x: 41.08545528760233, y: 279.3975263075628 },
    'incoming-worker': { x: 41.86980544355677, y: 385.3595148950661 },
    'incoming-schedule-process': { x: 42.275767414659654, y: 499.22613268329394 },
    'incoming-check-enqueue': { x: -167.7923461455415, y: 585.6896868077788 },
    'incoming-scheduled-at': { x: 41.74306730566859, y: 584.81119060383 },
    'postgres-main': { x: 328.22565957529923, y: 647.3785460113561 },
    'thread-write': { x: 497.29600890986853, y: 397.0476389503061 },
    'thread-metadata-write': { x: 498.95795155167866, y: 485.06836576799134 },
    'backfill-cursor-write': { x: 498.6470227487371, y: 573.3029324497704 },
    's3': { x: 749.1537393914566, y: 642.9898001566229 },
  },
  nodes: [
    triggerNode({
      id: 'trigger-oauth',
      label: 'Email Account Connected',
      description: 'External mailbox connection trigger that starts the mail pipeline.',
      notes: [
        'Stores Gmail auth state in mail_oauth_tokens.',
        'Resets the backfill cursor and kicks off the backfill start job.',
      ],
      position: { x: -270, y: -40 },
    }),
    queueNode({
      id: 'backfill-queue',
      label: 'Backfill Queue',
      notes: [
        'Holds both backfill start jobs and backfill chunk jobs.',
        'Uses mail_cursors.backfill_page_token to control paging.',
        'An empty token starts from the first page; a saved token resumes from that page.',
        'A done marker skips future fetch/enqueue for the mailbox.',
      ],
      position: { x: 110, y: -70 },
    }),
    workerNode({
      id: 'backfill-worker',
      label: 'Backfill Worker',
      description: 'Backfills historical mail for newly connected accounts.',
      notes: [
        'Consumes both backfill start jobs and backfill chunk jobs.',
        'Fetches historical threads, stores raw payloads, records thread metadata, and hands off extract work.',
      ],
      position: { x: 185, y: 60 },
      bullets: workerBullets,
      handles: [
        { position: 'top', type: 'target' },
        { id: 'out-bottom', position: 'bottom', type: 'source' },
        { id: 'out-right', position: 'right', type: 'source' },
        { id: 'out-left', position: 'left', type: 'source' },
      ],
    }),
    schedulerNode({ id: 'cron-scheduler', label: 'Cron Scheduler', description: 'Recurring scheduler boundary that decides when mailbox checks should run.', position: { x: 175, y: 220 } }),
    detailNode({ id: 'cron-enqueue', label: 'Enqueue Cron Tick', description: 'Queues the recurring cron tick that drives mailbox checks every minute.', position: { x: 150, y: 320 }, handles: [{ position: 'top', type: 'target' }, { position: 'bottom', type: 'source' }] }),
    queueNode({ id: 'incoming-queue', label: 'Incoming Queue', notes: ['Holds both the recurring mailbox-sweep work and mailbox incoming-check work.', 'Jobs can arrive from multiple vendors and mailboxes.'], position: { x: 145, y: 405 }, handles: [{ id: 'in-top', position: 'top', type: 'target' }, { id: 'in-left', position: 'left', type: 'target' }, { id: 'out-bottom', position: 'bottom', type: 'source' }] }),
    workerNode({ id: 'incoming-worker', label: 'Incoming Worker', description: 'Checks connected inboxes for new mail and hands off downstream work.', notes: ['Picks up both scheduled mailbox-sweep work and mailbox incoming-check work from the Incoming Queue.', 'If no incoming_history_id exists yet, incoming processing writes the baseline cursor and stops.'], position: { x: 205, y: 535 }, bullets: workerBullets, handles: [{ position: 'top', type: 'target' }, { id: 'out-right', position: 'right', type: 'source' }, { id: 'out-bottom', position: 'bottom', type: 'source' }] }),

    detailNode({ id: 'incoming-schedule-process', label: 'Schedule Incoming Checks', description: 'Finds mailboxes that should get an incoming check and prepares the next queue work.', notes: ['Reads connected mailbox rows from mail_oauth_tokens.', 'Looks up mail_cursors.incoming_check_scheduled_at to find mailboxes due for a check.'], position: { x: -455, y: 702 }, handles: [{ id: 'in-top', position: 'top', type: 'target' }, { id: 'out-bottom', position: 'bottom', type: 'source' }] }),
    detailNode({ id: 'incoming-check-enqueue', label: 'Enqueue Incoming Check', description: 'Queues a mailbox incoming check when unread mail should be processed.', position: { x: -555, y: 815 }, handles: [{ id: 'in-top', position: 'top', type: 'target' }, { id: 'out-left', position: 'left', type: 'source' }] }),
    detailNode({ id: 'incoming-scheduled-at', label: 'Write Schedule Cursor', description: 'Updates the scheduled incoming-check cursor timestamp in Postgres.', notes: ['Writes mail_cursors.incoming_check_scheduled_at in Postgres.', 'Marks when the mailbox was last scheduled for an incoming check.'], position: { x: -340, y: 815 }, handles: [{ id: 'in-top', position: 'top', type: 'target' }, { id: 'out-right', position: 'right', type: 'source' }] }),

    resourceNode({
      id: 'postgres-main',
      label: 'Postgres',
      style: { icon: 'postgres' },
      description: 'Primary relational store for mail auth, cursors, and thread state.',
      notes: [
        'Stores mailbox auth state in mail_oauth_tokens.',
        'Stores backfill and incoming cursors in mail_cursors.',
        'Stores normalized thread state in mail_threads.',
      ],
      position: { x: 250, y: 715 },
      handles: [
        { id: 'in-left', position: 'left', type: 'target' },
        { id: 'in-right', position: 'right', type: 'target' },
      ],
    }),

    detailNode({
      id: 'thread-write',
      label: 'Write Threads',
      description: 'Stores raw mailbox thread payloads in the thread artifact store.',
      notes: [
        'Used by both backfill and incoming ingest.',
        'Writes one stored thread artifact per mailbox thread payload.',
      ],
      position: { x: 365, y: 600 },
      handles: [
        { id: 'in-left', position: 'left', type: 'target' },
        { id: 'in-top', position: 'top', type: 'target' },
        { id: 'out-right', position: 'right', type: 'source' },
        { id: 'out-bottom', position: 'bottom', type: 'source' },
      ],
    }),
    detailNode({
      id: 'thread-metadata-write',
      label: 'Write Thread Metadata',
      description: 'Upserts normalized thread state into Postgres.',
      notes: [
        'Used by both backfill and incoming ingest.',
        'Writes mail_threads rows with s3_key, content_hash, subject, participants, and ingest timestamp.',
      ],
      position: { x: 365, y: 730 },
      handles: [
        { id: 'in-top', position: 'top', type: 'target' },
        { id: 'out-bottom', position: 'bottom', type: 'source' },
      ],
    }),
    detailNode({
      id: 'backfill-cursor-write',
      label: 'Write Backfill Cursor',
      description: 'Updates the backfill cursor state in Postgres.',
      notes: [
        'Writes the next mail_cursors.backfill_page_token value or the done marker.',
        'When another page exists, this step also schedules the next backfill chunk job.',
      ],
      position: { x: 565, y: 790 },
      handles: [
        { id: 'in-top', position: 'top', type: 'target' },
        { id: 'out-bottom', position: 'bottom', type: 'source' },
      ],
    }),

    resourceNode({
      id: 's3',
      label: 'S3',
      style: { icon: 's3' },
      description: 'Thread artifact store for raw mailbox thread data.',
      notes: [
        'Receives raw thread artifacts from both backfill and incoming ingest.',
        'One stored artifact corresponds to one mailbox thread payload.',
      ],
      position: { x: 950, y: 650 },
      handles: [
        { id: 'in-left', position: 'left', type: 'target' },
        { id: 'in-top', position: 'top', type: 'target' },
      ],
    }),

    detailGroup({ id: 'incoming-normal-group', label: '', position: { x: 500, y: 970 }, size: { width: 345, height: 240 }, handles: [{ id: 'in-top', position: 'top', type: 'target' }] }),
    detailNode({ id: 'extract-enqueue', label: 'Enqueue Extract', description: 'Queues extract work for the newly stored thread payload.', position: { x: 58, y: 28 }, parentId: 'incoming-normal-group', handles: [{ id: 'in-top', position: 'top', type: 'target' }, { id: 'out-right', position: 'right', type: 'source' }] }),
    detailNode({ id: 'analyze-enqueue', label: 'Enqueue Analyze', description: 'Queues analyze work for the stored thread and extracted context.', position: { x: 40, y: 90 }, parentId: 'incoming-normal-group', handles: [{ id: 'in-top', position: 'top', type: 'target' }, { id: 'out-right', position: 'right', type: 'source' }] }),
    detailNode({ id: 'update-history', label: 'Update History Cursor', description: 'Updates the incoming history cursor after new mail has been stored.', position: { x: 35, y: 152 }, parentId: 'incoming-normal-group', handles: [{ id: 'in-top', position: 'top', type: 'target' }] }),

    queueNode({ id: 'analyze-queue', label: 'Analyze Queue', position: { x: 980, y: 1010 }, layout: { order: 56 }, handles: [{ id: 'in-left', position: 'left', type: 'target' }, { id: 'out-bottom', position: 'bottom', type: 'source' }] }),
    workerNode({ id: 'analyze-worker', label: 'Analyze Worker', description: 'Analyzes extracted mail and decides whether to draft a reply.', position: { x: 1005, y: 1160 }, bullets: workerBullets, layout: { lane: 'main', order: 58 } }),
    decisionNode({ id: 'analyze-decision', label: 'Next Action?', description: 'Runs propose-mode analysis to choose the next thread action after prechecks pass.', notes: ['Prechecks run before the LLM branch.', 'The LLM can return skip, needs_review, or draft_reply.'], position: { x: 1035, y: 1355 }, layout: { lane: 'main', order: 60 } }),

    detailNode({ id: 'skip-owner-stop', label: 'Skip Internal Sender', description: 'Stops analyze when the latest sender is the mailbox owner.', position: { x: 1275, y: 1370 }, layout: { lane: 'branch', order: 61, branch: { anchorId: 'analyze-decision', track: 'right', rank: 0, domain: 'analyze', column: 0 } } }),
    detailNode({ id: 'reuse-batch-stop', label: 'Reuse Batch', description: 'Reuses the existing active action batch instead of creating a new one.', position: { x: 1300, y: 1470 }, layout: { lane: 'branch', order: 62, branch: { anchorId: 'analyze-decision', track: 'right', rank: 1, domain: 'analyze', column: 0 } } }),
    detailNode({ id: 'skip-thread-status', label: 'Mark Skipped', description: 'Marks the thread as skipped and ends this branch.', position: { x: 1310, y: 1570 }, layout: { lane: 'branch', order: 63, branch: { anchorId: 'analyze-decision', track: 'right', rank: 2, domain: 'analyze', column: 0 } } }),
    detailNode({ id: 'analyze-error', label: 'Needs Review', description: 'Falls back to needs_review when analyze returns an error or malformed output.', position: { x: 1210, y: 1665 }, layout: { lane: 'branch', order: 66, branch: { anchorId: 'analyze-decision', track: 'right', rank: 3, domain: 'analyze', column: 0, dx: 0, dy: 8 } } }),
    decisionNode({ id: 'supported-actions', label: 'Supported Actions?', description: 'Checks whether analyze produced a supported action set we can continue with.', position: { x: 1035, y: 1595 }, layout: { lane: 'main', order: 64, branch: { anchorId: 'analyze-decision', track: 'primary', rank: 0 } } }),

    stepNode({ id: 'draft-reply', label: 'Draft Reply', description: 'Writes the reply draft record before approval or send decisions continue.', position: { x: 930, y: 1780 }, layout: { lane: 'main', order: 68, branch: { anchorId: 'supported-actions-outcome', track: 'primary', rank: 0 } } }),
    detailNode({ id: 'unsupported-actions-outcome', label: 'Write Review Draft', description: 'Creates the draft and marks both draft and thread state as needs_review.', position: { x: 1270, y: 1780 }, layout: { lane: 'branch', order: 65, branch: { anchorId: 'supported-actions', track: 'right', rank: 0, domain: 'analyze', column: 0, dx: 10 } } }),
    detailNode({ id: 'pause-manual-review', label: 'Pause Review', description: 'Stops the flow until someone reviews the draft manually.', position: { x: 1335, y: 1940 }, layout: { lane: 'branch', order: 67, branch: { anchorId: 'unsupported-actions-outcome', track: 'primary', rank: 0, dy: 4 } } }),
    detailNode({ id: 'supported-actions-outcome', label: 'Write Pending Draft', description: 'Creates the draft, writes approval-pending state, and creates the action batch.', position: { x: 875, y: 1945 }, layout: { lane: 'main', order: 70, branch: { anchorId: 'supported-actions', track: 'primary', rank: 0, dy: 10 } } }),

    decisionNode({ id: 'autosend-decision', label: 'Auto Send?', description: 'Checks whether autosend is enabled and the action batch can be auto-approved.', position: { x: 1035, y: 2145 }, layout: { lane: 'main', order: 72, branch: { anchorId: 'draft-reply', track: 'primary', rank: 0 } } }),
    detailNode({ id: 'pause-manual-approval', label: 'Pause Approval', description: 'Stops the flow until someone manually approves the pending action batch.', position: { x: 1290, y: 2195 }, layout: { lane: 'branch', order: 73, branch: { anchorId: 'autosend-decision', track: 'right', rank: 0, domain: 'approval', column: 0, dx: 10 } } }),
    detailNode({ id: 'manual-approval-api', label: 'Approve Batch', description: 'Manual approval path that approves the batch and enqueues the approved-actions job.', position: { x: 1280, y: 2335 }, layout: { lane: 'branch', order: 74, branch: { anchorId: 'pause-manual-approval', track: 'primary', rank: 0 } } }),
    detailNode({ id: 'autosend-approved', label: 'Auto Approve', description: 'Auto-approves the batch, updates thread state, and enqueues the approved-actions job.', position: { x: 835, y: 2325 }, layout: { lane: 'main', order: 76, branch: { anchorId: 'autosend-decision', track: 'primary', rank: 0, dy: 6 } } }),

    queueNode({ id: 'actions-queue', label: 'Actions Queue', position: { x: 985, y: 2525 }, layout: { lane: 'main', order: 77 }, handles: [{ id: 'in-top', position: 'top', type: 'target' }, { id: 'out-bottom', position: 'bottom', type: 'source' }] }),
    workerNode({ id: 'actions-worker', label: 'Actions Worker', description: 'Executes approved actions and hands off send jobs.', position: { x: 1005, y: 2670 }, bullets: workerBullets, layout: { lane: 'main', order: 78 } }),

    detailGroup({ id: 'actions-process-group', label: '', position: { x: 895, y: 2820 }, size: { width: 430, height: 255 } }),
    detailNode({ id: 'process-approved-action', label: 'Run Actions', description: 'Executes the approved send action before the send job handoff.', position: { x: 82, y: 24 }, parentId: 'actions-process-group' }),
    detailNode({ id: 'mark-draft-needs-review', label: 'Mark Review', description: 'Marks the draft as needs_review before the send handoff continues.', position: { x: 82, y: 103 }, parentId: 'actions-process-group' }),
    detailNode({ id: 'enqueue-send-reply', label: 'Queue Send', description: 'Enqueues send-reply work and marks the thread as sending.', position: { x: 82, y: 177 }, parentId: 'actions-process-group' }),

    queueNode({ id: 'extract-queue', label: 'Extract Queue', notes: ['Contains both handle_mail_extract and handle_mail_recompute_opportunities.', 'AI provider credentials are required only for handle_mail_extract.'], position: { x: 1565, y: 900 }, layout: { lane: 'sidecar', order: 64 }, handles: [{ id: 'in-left', position: 'left', type: 'target' }, { id: 'out-bottom', position: 'bottom', type: 'source' }] }),
    workerNode({ id: 'extract-worker', label: 'Extract Worker', description: 'Extracts structured contact and thread details from stored mail.', position: { x: 1580, y: 1035 }, bullets: workerBullets, layout: { lane: 'sidecar', order: 68 } }),
    detailNode({ id: 'extract-ai', label: 'Run Extract', description: 'Loads the stored thread payload and runs AI extraction.', position: { x: 1545, y: 1215 }, layout: { lane: 'sidecar', order: 70 } }),
    decisionNode({ id: 'extract-ai-success', label: 'Extract Succeeded?', description: 'Checks whether the extract step produced a usable result.', position: { x: 1615, y: 1405 }, layout: { lane: 'sidecar', order: 72, branch: { anchorId: 'extract-ai', track: 'primary', rank: 0 } } }),
    detailNode({ id: 'extract-fail-1', label: 'Retry Extract', description: 'Records extract error state and returns a retryable job error.', position: { x: 1905, y: 1455 }, layout: { lane: 'branch', order: 73, branch: { anchorId: 'extract-ai-success', track: 'right', rank: 0, domain: 'extract', column: 1 } } }),
    detailNode({ id: 'upsert-contacts', label: 'Upsert Contacts', description: 'Writes normalized contact rows into mail_extracted_contacts.', notes: ['Normalize emails.', 'Dedupe per thread.', 'Prefer higher-confidence and richer non-empty fields.', 'Never overwrite non-empty stored fields with empty values.'], position: { x: 1535, y: 1605 }, layout: { lane: 'sidecar', order: 74, branch: { anchorId: 'extract-ai-success', track: 'primary', rank: 0 } } }),
    resourceNode({ id: 'postgres-extract', label: 'Postgres', style: { icon: 'postgres' }, position: { x: 2050, y: 1635 }, layout: { lane: 'resource', order: 75 }, handles: [{ id: 'in-left', position: 'left', type: 'target' }] }),
    decisionNode({ id: 'contact-upsert-success', label: 'Upsert Succeeded?', description: 'Checks whether the contact upsert completed successfully.', position: { x: 1615, y: 1795 }, layout: { lane: 'sidecar', order: 76, branch: { anchorId: 'upsert-contacts', track: 'primary', rank: 0 } } }),
    detailNode({ id: 'extract-fail-2', label: 'Retry Extract', description: 'Records extract error state and returns a retryable job error.', position: { x: 1905, y: 1850 }, layout: { lane: 'branch', order: 77, branch: { anchorId: 'contact-upsert-success', track: 'right', rank: 0, domain: 'extract', column: 1 } } }),
    detailNode({ id: 'extract-record-success', label: 'Record Extract State', description: 'Stores the extract summary, including the identified customer count.', position: { x: 1535, y: 1995 }, layout: { lane: 'sidecar', order: 78, branch: { anchorId: 'contact-upsert-success', track: 'primary', rank: 0 } }, handles: [{ id: 'in-top', position: 'top', type: 'target' }, { id: 'out-bottom', position: 'bottom', type: 'source' }, { id: 'out-right', position: 'right', type: 'source' }] }),
    detailNode({ id: 'recompute-enqueue', label: 'Enqueue Recompute', description: 'Queues recompute-opportunities work with mailbox-level debouncing.', position: { x: 1825, y: 1965 }, layout: { lane: 'branch', order: 79, branch: { anchorId: 'extract-record-success', track: 'right', rank: 0, domain: 'extract', column: 0, dx: -80, dy: -8 } }, handles: [{ id: 'in-left', position: 'left', type: 'target' }, { id: 'out-left', position: 'left', type: 'source' }] }),
    stepNode({ id: 'recompute-process', label: 'Recompute Opportunities', description: 'Recomputes follow-up opportunities for the mailbox after extract state changes.', notes: ['Scans mail_extracted_contacts for the mailbox.', 'Upserts or deletes follow_up_opportunities.'], position: { x: 1845, y: 1180 }, layout: { lane: 'branch', order: 69, branch: { anchorId: 'extract-worker', track: 'right', rank: 0, domain: 'extract', column: 1, dx: -20, dy: -12 } } }),

    queueNode({ id: 'send-queue', label: 'Send Queue', position: { x: 985, y: 3135 }, handles: [{ id: 'in-top', position: 'top', type: 'target' }, { id: 'out-bottom', position: 'bottom', type: 'source' }] }),
    workerNode({ id: 'send-worker', label: 'Send Worker', description: 'Validates and sends reply drafts through the provider.', position: { x: 1005, y: 3280 }, bullets: workerBullets }),
    stepNode({ id: 'send-process', label: 'Send Reply', description: 'Owns the send lifecycle after the send worker picks up the job.', position: { x: 1005, y: 3450 } }),

    detailGroup({ id: 'send-process-group', label: '', position: { x: 615, y: 3580 }, size: { width: 820, height: 430 }, handles: [] }),
    detailNode({ id: 'send-prechecks', label: 'Validate + Send', description: 'Runs idempotency, freshness, auth, recipient, and body checks before the Gmail API send.', position: { x: 210, y: 40 }, parentId: 'send-process-group' }),
    detailNode({ id: 'send-success', label: 'Mark Sent', description: 'Marks both the draft and thread as sent after the provider call succeeds.', position: { x: 30, y: 170 }, parentId: 'send-process-group' }),
    detailNode({ id: 'send-nonretry', label: 'Mark Send Failed', description: 'Marks the draft as send_failed and the thread as send_failed or stale.', position: { x: 260, y: 300 }, parentId: 'send-process-group' }),
    detailNode({ id: 'send-retry', label: 'Mark Needs Review', description: 'Moves the draft and thread back to needs_review after a retryable send failure.', position: { x: 580, y: 170 }, parentId: 'send-process-group' }),
  ],

  edges: [
    { id: 'e-trigger-backfill', source: 'trigger-oauth', target: 'backfill-queue' },
    { id: 'e-backfill-q-worker', source: 'backfill-queue', target: 'backfill-worker' },
    {
      id: 'e-backfill-write-threads',
      source: 'backfill-worker',
      sourceHandle: 'backfill-worker-out-bottom',
      target: 'thread-write',
      targetHandle: 'thread-write-in-top',
    },
    {
      id: 'e-thread-write-metadata',
      source: 'thread-write',
      sourceHandle: 'thread-write-out-bottom',
      target: 'thread-metadata-write',
      targetHandle: 'thread-metadata-write-in-top',
    },
    {
      id: 'e-thread-write-s3',
      source: 'thread-write',
      sourceHandle: 'thread-write-out-right',
      target: 's3',
      targetHandle: 's3-in-top',
    },
    {
      id: 'e-thread-metadata-postgres',
      source: 'thread-metadata-write',
      sourceHandle: 'thread-metadata-write-out-bottom',
      target: 'postgres-main',
      targetHandle: 'postgres-main-in-right',
    },
    {
      id: 'e-backfill-cursor-write',
      source: 'thread-metadata-write',
      sourceHandle: 'thread-metadata-write-out-bottom',
      target: 'backfill-cursor-write',
      targetHandle: 'backfill-cursor-write-in-top',
    },
    {
      id: 'e-backfill-cursor-postgres',
      source: 'backfill-cursor-write',
      sourceHandle: 'backfill-cursor-write-out-bottom',
      target: 'postgres-main',
      targetHandle: 'postgres-main-in-right',
    },
    {
      id: 'e-backfill-extract-queue',
      source: 'backfill-worker',
      sourceHandle: 'backfill-worker-out-right',
      target: 'extract-queue',
      targetHandle: 'extract-queue-in-left',
    },

    { id: 'e-cron-enqueue', source: 'cron-scheduler', target: 'cron-enqueue' },
    { id: 'e-cron-enqueue-incoming', source: 'cron-enqueue', target: 'incoming-queue', targetHandle: 'incoming-queue-in-top' },
    { id: 'e-incoming-q-worker', source: 'incoming-queue', sourceHandle: 'incoming-queue-out-bottom', target: 'incoming-worker' },

    {
      id: 'e-incoming-worker-schedule',
      source: 'incoming-worker',
      sourceHandle: 'incoming-worker-out-bottom',
      target: 'incoming-schedule-process',
      targetHandle: 'incoming-schedule-process-in-top',
    },
    {
      id: 'e-schedule-enqueue',
      source: 'incoming-schedule-process',
      sourceHandle: 'incoming-schedule-process-out-bottom',
      target: 'incoming-check-enqueue',
      targetHandle: 'incoming-check-enqueue-in-top',
    },
    {
      id: 'e-schedule-cursor',
      source: 'incoming-schedule-process',
      sourceHandle: 'incoming-schedule-process-out-bottom',
      target: 'incoming-scheduled-at',
      targetHandle: 'incoming-scheduled-at-in-top',
    },
    {
      id: 'e-schedule-postgres',
      source: 'incoming-scheduled-at',
      sourceHandle: 'incoming-scheduled-at-out-right',
      target: 'postgres-main',
      targetHandle: 'postgres-main-in-left',
    },
    {
      id: 'e-incoming-check-enqueue-queue',
      source: 'incoming-check-enqueue',
      sourceHandle: 'incoming-check-enqueue-out-left',
      target: 'incoming-queue',
      targetHandle: 'incoming-queue-in-left',
    },

    {
      id: 'e-incoming-write-threads',
      source: 'incoming-worker',
      sourceHandle: 'incoming-worker-out-right',
      target: 'thread-write',
      targetHandle: 'thread-write-in-left',
    },
    {
      id: 'e-incoming-normal',
      source: 'incoming-worker',
      sourceHandle: 'incoming-worker-out-right',
      target: 'incoming-normal-group',
      targetHandle: 'incoming-normal-group-in-top',
    },
    {
      id: 'e-analyze-enqueue-queue',
      source: 'analyze-enqueue',
      sourceHandle: 'analyze-enqueue-out-right',
      target: 'analyze-queue',
      targetHandle: 'analyze-queue-in-left',
    },
    {
      id: 'e-extract-enqueue-queue',
      source: 'extract-enqueue',
      sourceHandle: 'extract-enqueue-out-right',
      target: 'extract-queue',
      targetHandle: 'extract-queue-in-left',
    },

    { id: 'e-analyze-q-worker', source: 'analyze-queue', sourceHandle: 'analyze-queue-out-bottom', target: 'analyze-worker' },
    { id: 'e-analyze-worker-decision', source: 'analyze-worker', target: 'analyze-decision', targetHandle: 'analyze-decision-in-top' },
    { id: 'e-analyze-skip-owner', source: 'analyze-decision', sourceHandle: 'analyze-decision-out-right', target: 'skip-owner-stop' },
    { id: 'e-analyze-reuse-batch', source: 'analyze-decision', sourceHandle: 'analyze-decision-out-right', target: 'reuse-batch-stop' },
    {
      id: 'e-analyze-skip-status',
      source: 'analyze-decision',
      sourceHandle: 'analyze-decision-out-right',
      target: 'skip-thread-status',
      label: 'action = skip',
    },
    {
      id: 'e-analyze-error',
      source: 'analyze-decision',
      sourceHandle: 'analyze-decision-out-right',
      target: 'analyze-error',
    },
    {
      id: 'e-analyze-supported-actions',
      source: 'analyze-decision',
      sourceHandle: 'analyze-decision-out-bottom',
      target: 'supported-actions',
      targetHandle: 'supported-actions-in-top',
      label: 'action = draft_reply',
    },
    {
      id: 'e-supported-actions-no',
      source: 'supported-actions',
      sourceHandle: 'supported-actions-out-right',
      target: 'unsupported-actions-outcome',
      label: 'No',
    },
    {
      id: 'e-supported-actions-yes',
      source: 'supported-actions',
      sourceHandle: 'supported-actions-out-bottom',
      target: 'supported-actions-outcome',
      label: 'Yes',
    },
    { id: 'e-unsupported-pause', source: 'unsupported-actions-outcome', target: 'pause-manual-review' },
    { id: 'e-supported-draft', source: 'supported-actions-outcome', target: 'draft-reply' },
    { id: 'e-draft-autosend', source: 'draft-reply', target: 'autosend-decision', targetHandle: 'autosend-decision-in-top' },
    {
      id: 'e-autosend-pause',
      source: 'autosend-decision',
      sourceHandle: 'autosend-decision-out-right',
      target: 'pause-manual-approval',
      label: 'No',
    },
    {
      id: 'e-autosend-approve',
      source: 'autosend-decision',
      sourceHandle: 'autosend-decision-out-bottom',
      target: 'autosend-approved',
      label: 'Yes',
    },
    { id: 'e-pause-manual-api', source: 'pause-manual-approval', target: 'manual-approval-api' },
    { id: 'e-autosend-actions', source: 'autosend-approved', target: 'actions-queue', targetHandle: 'actions-queue-in-top' },
    { id: 'e-manual-actions', source: 'manual-approval-api', target: 'actions-queue', targetHandle: 'actions-queue-in-top' },
    { id: 'e-actions-q-worker', source: 'actions-queue', sourceHandle: 'actions-queue-out-bottom', target: 'actions-worker' },
    { id: 'e-actions-worker-process', source: 'actions-worker', target: 'process-approved-action' },
    { id: 'e-actions-mark-review', source: 'process-approved-action', target: 'mark-draft-needs-review' },
    { id: 'e-actions-enqueue-send', source: 'mark-draft-needs-review', target: 'enqueue-send-reply' },
    { id: 'e-actions-send', source: 'enqueue-send-reply', target: 'send-queue', targetHandle: 'send-queue-in-top' },

    { id: 'e-extract-q-worker', source: 'extract-queue', sourceHandle: 'extract-queue-out-bottom', target: 'extract-worker' },
    { id: 'e-extract-worker-ai', source: 'extract-worker', target: 'extract-ai' },
    { id: 'e-extract-ai-success', source: 'extract-ai', target: 'extract-ai-success', targetHandle: 'extract-ai-success-in-top' },
    {
      id: 'e-extract-fail-1',
      source: 'extract-ai-success',
      sourceHandle: 'extract-ai-success-out-right',
      target: 'extract-fail-1',
      label: 'No',
    },
    {
      id: 'e-extract-upsert',
      source: 'extract-ai-success',
      sourceHandle: 'extract-ai-success-out-bottom',
      target: 'upsert-contacts',
      label: 'Yes',
    },
    { id: 'e-upsert-postgres', source: 'upsert-contacts', target: 'postgres-extract', targetHandle: 'postgres-extract-in-left' },
    { id: 'e-upsert-success', source: 'upsert-contacts', target: 'contact-upsert-success', targetHandle: 'contact-upsert-success-in-top' },
    {
      id: 'e-extract-fail-2',
      source: 'contact-upsert-success',
      sourceHandle: 'contact-upsert-success-out-right',
      target: 'extract-fail-2',
      label: 'No',
    },
    {
      id: 'e-extract-record-success',
      source: 'contact-upsert-success',
      sourceHandle: 'contact-upsert-success-out-bottom',
      target: 'extract-record-success',
      label: 'Yes',
    },
    {
      id: 'e-extract-recompute-enqueue',
      source: 'extract-record-success',
      sourceHandle: 'extract-record-success-out-right',
      target: 'recompute-enqueue',
      targetHandle: 'recompute-enqueue-in-left',
    },
    {
      id: 'e-recompute-enqueue-queue',
      source: 'recompute-enqueue',
      sourceHandle: 'recompute-enqueue-out-left',
      target: 'extract-queue',
      targetHandle: 'extract-queue-in-left',
    },
    {
      id: 'e-extract-worker-recompute',
      source: 'extract-worker',
      target: 'recompute-process',
      label: 'execute handle_mail_recompute_opportunities',
    },

    { id: 'e-send-q-worker', source: 'send-queue', sourceHandle: 'send-queue-out-bottom', target: 'send-worker' },
    { id: 'e-send-worker-process', source: 'send-worker', target: 'send-process' },
    { id: 'e-send-process-prechecks', source: 'send-process', target: 'send-prechecks' },
    {
      id: 'e-send-success-branch',
      source: 'send-prechecks',
      target: 'send-success',
      label: 'success',
    },
    {
      id: 'e-send-retry-branch',
      source: 'send-prechecks',
      target: 'send-retry',
      label: 'retryable failure',
    },
    {
      id: 'e-send-nonretry-branch',
      source: 'send-prechecks',
      target: 'send-nonretry',
      label: 'non-retryable failure',
    },
  ],
  producerMapping,
  spanMapping,
}
